### ISSUE TITLE
Duplicate affix rule

### ISSUE THREAD

**Issue by shantanuo** [Shreeshrii/hindi-hunspell#10]
The following rule in affix file is duplicated. Please remove one line.

SFX 3 ी िए ी

Use the validator found here...

https://proofingtoolgui.org/

**Comment by Shreeshrii** [comment]
Done via https://github.com/Shreeshrii/hindi-hunspell/commit/405368a52868ea01f17d583624bdfdded9c98230

Thanks!

**Comment by shantanuo** [comment]
After removing a line you will also have to change the count from 17 to 16 for that rule.

SFX	3	Y	17
