### ISSUE TITLE
It generates so few files

### ISSUE THREAD

**Issue by MonsterMMORPG** [Shreeshrii/hindi-hunspell#2]
I have tried to generate all forms of Arabic words in this dictionary

https://github.com/linuxscout/ayaspell/tree/master/dict

It generated only 294224 words

I know there are millions of valid cases

Any idea why?

Here my modified unmunchit.sh file

```
LC_ALL=ar_AE.utf8  ../tools/unmunch.sh \
../Arab/arb_alias.dic \
../Arab/arb_alias.aff  \
> results.txt

```

**Comment by Shreeshrii** [comment]
not related to hindi or sanskrit hunspell dictionary.
