### ISSUE TITLE
Read tables with Tesseract OCR

### ISSUE THREAD

**Issue by Chandrahar** [Shreeshrii/hindi-hunspell#3]
Convert PDF of tables to CSV-formatted tables.

**Comment by Shreeshrii** [comment]
Please open issue in tesseract OCR project.

**Comment by Chandrahar** [comment]
Hi sir
Actually i want to Post One Project regarding tesseract OCR so i am trying
to post project but i am not getting...
Just i want to make one utility
where application accept batch of pdf file as input & generate each excel
file as output....

Note : all pdf files are (Indian regional language )

so if anyone is taking project call me
9623994097
email : aug.idcard@gmail.com

**Comment by Chandrahar** [comment]
please help me....

**Comment by Chandrahar** [comment]
Please reply
